package model;

public enum ContentTags {
  SPORTS, ART, STEM, SCIENCE, CAREER, LAW, BUSINESS, FORMAL,
  MUSIC, DANCE, HOLIDAY, BIRTHDAY, COSTUME, WEDDING, FITNESS,
  HEALTH, DESIGN, RECREATION, WORKSHOP, ACADEMIC, GREEK_LIFE,
  ADVOCACY
}
